# --- MINIO PLATFORM RESOURCES -------------------------------------------------
# MinIO Tenant and configuration secrets
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: minio-platform

resources:
  - tenant.yaml
