# --- PARAMETRIC-PORTAL PROJECT BASE ------------------------------------------
# Project-specific base resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: parametric-portal-project-base

resources:
  - PROJECT.yaml
  - domains.yaml
  - certificate.yaml
